### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/re2/lib/libre2.so.0

### ISSUE THREAD

**Issue by toohsk** [jubatus/homebrew-jubatus#17]
Hi, I'm trying to execute twitter streaming location example, but I cannot start jubaclassifier which installed jubatus from home-brew.
I've got an error as bellow.

knowtice that, current directory is directory of `jubatus-example/twitter_streaming_location/`

```
jubaclassifier -f twitter_streaming_location.json
dyld: Library not loaded: /usr/local/opt/re2/lib/libre2.so.0
  Referenced from: /usr/local/lib/libjubatus_core.dylib
  Reason: image not found
[1]    47983 trace trap  jubaclassifier -f twitter_streaming_location.json
```

Before making this issue, I've read #15 , and tried update my homebrew and reinstall jubatus with options  as bellow, of course I've tried no options but I couldn't start jubaclassifer.

```
brew uninstall jubatus jubatus-core jubatus-mpio jubatus-msgpack-rpc
brew install jubatus-core --use-clang --regexp-library=re2
brew install jubatus --use-clang --enable-mecab
```

Is there any problems with my installing or starting jubaclassifier?

**Comment by kmaehashi** [comment]
* What OS X version are you on? (Mavericks or Yosemite?)
* Have you tried reinstalling re2?

**Comment by toohsk** [comment]
thanks for quick reply.

My OS X version is Yosemite.
When I installed jubatus-core using `--regexp-library=re2` option, re2 library has been installed too as bellow.
```
brew install jubatus-core --use-clang --regexp-library=re2
==> Installing jubatus-core dependency: re2
==> Downloading https://re2.googlecode.com/files/re2-20140304.tgz
######################################################################## 100.0%
==> make install prefix=/usr/local/Cellar/re2/20140304
🍺  /usr/local/Cellar/re2/20140304: 11 files, 1.2M, built in 8 seconds
==> Installing jubatus-core
==> Downloading https://github.com/jubatus/jubatus_core/tarball/0.0.7
Already downloaded: /Library/Caches/Homebrew/jubatus-core-0.0.7.7
==> ./waf configure --prefix=/usr/local/Cellar/jubatus-core/0.0.7 --regexp-libra
==> ./waf
==> ./waf install
🍺  /usr/local/Cellar/jubatus-core/0.0.7: 528 files, 9.0M, built in 51 seconds
```

**Comment by kmaehashi** [comment]
```
dyld: Library not loaded: /usr/local/opt/re2/lib/libre2.so.0
```

Hmm, your re2 installation seems broken. Could you please try reinstalling it?

```
brew uninstall re2 jubatus jubatus-core
brew install jubatus-core --use-clang --regexp-library=re2
brew install jubatus --use-clang --enable-mecab
```

Alternatively, you can probably workaround this problem by using oniguruma instead of re2.

```
brew uninstall jubatus jubatus-core
brew install jubatus --use-clang
```

**Comment by toohsk** [comment]
I'd tried reinstall `re2`, but it didn't change.
And after uninstall and reinstall jubatus, but seems still not work.

If you won't mind, I want to try some actions so would you keep open this issue for a while?

**Comment by kmaehashi** [comment]
The root cause of this issue has been solved via https://github.com/jubatus/jubatus/pull/1181 in Jubatus 1.0.2 release.
