### ISSUE TITLE
Use SHA256 instead of deprecated SHA1 in Homebrew formulae

### ISSUE THREAD

**Issue by shiodat** [jubatus/homebrew-jubatus#22]
As the title says, we use `sha1`, which is deprecated by Homebrew.
We should use `sha256`, as recommended by `brew` audit.

The warning messages are as follows:

> Warning: SHA1 support is deprecated and will be removed in a future version.
> Please switch this formula to SHA256.

**Comment by kmaehashi** [comment]
Oops, other fomulas (jubatus-mpio etc) are still using SHA1 sum.

**Comment by shiodat** [comment]
Sorry, I fixed other formulas. #25

**Comment by nixsiow** [comment]
Hello, I am facing the same error and it ask to report to the karan/karan tap. What should I do? Thanks!
